// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	models "grabarr/internal/models"
)

// MockRemoteFileRepo is an autogenerated mock type for the RemoteFileRepo type
type MockRemoteFileRepo struct {
	mock.Mock
}

type MockRemoteFileRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteFileRepo) EXPECT() *MockRemoteFileRepo_Expecter {
	return &MockRemoteFileRepo_Expecter{mock: &_m.Mock}
}

// GetRemoteFiles provides a mock function with given fields: filter
func (_m *MockRemoteFileRepo) GetRemoteFiles(filter models.RemoteFileFilter) ([]*models.RemoteFile, error) {
	ret := _m.Called(filter)

	var r0 []*models.RemoteFile
	if rf, ok := ret.Get(0).(func(models.RemoteFileFilter) []*models.RemoteFile); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RemoteFile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.RemoteFileFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRemoteFileRepo_GetRemoteFiles_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) GetRemoteFiles(filter interface{}) *MockRemoteFileRepo_GetRemoteFiles_Call {
	return &MockRemoteFileRepo_GetRemoteFiles_Call{Call: _e.mock.On("GetRemoteFiles", filter)}
}

func (_c *MockRemoteFileRepo_GetRemoteFiles_Call) Run(run func(filter models.RemoteFileFilter)) *MockRemoteFileRepo_GetRemoteFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.RemoteFileFilter))
	})
	return _c
}

func (_c *MockRemoteFileRepo_GetRemoteFiles_Call) Return(files []*models.RemoteFile, err error) *MockRemoteFileRepo_GetRemoteFiles_Call {
	_c.Call.Return(files, err)
	return _c
}

// CountRemoteFiles provides a mock function with given fields: filter
func (_m *MockRemoteFileRepo) CountRemoteFiles(filter models.RemoteFileFilter) (int, error) {
	ret := _m.Called(filter)

	var r0 int
	if rf, ok := ret.Get(0).(func(models.RemoteFileFilter) int); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.RemoteFileFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRemoteFileRepo_CountRemoteFiles_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) CountRemoteFiles(filter interface{}) *MockRemoteFileRepo_CountRemoteFiles_Call {
	return &MockRemoteFileRepo_CountRemoteFiles_Call{Call: _e.mock.On("CountRemoteFiles", filter)}
}

func (_c *MockRemoteFileRepo_CountRemoteFiles_Call) Run(run func(filter models.RemoteFileFilter)) *MockRemoteFileRepo_CountRemoteFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.RemoteFileFilter))
	})
	return _c
}

func (_c *MockRemoteFileRepo_CountRemoteFiles_Call) Return(count int, err error) *MockRemoteFileRepo_CountRemoteFiles_Call {
	_c.Call.Return(count, err)
	return _c
}

// GetRemoteFile provides a mock function with given fields: id
func (_m *MockRemoteFileRepo) GetRemoteFile(id int64) (*models.RemoteFile, error) {
	ret := _m.Called(id)

	var r0 *models.RemoteFile
	if rf, ok := ret.Get(0).(func(int64) *models.RemoteFile); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RemoteFile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRemoteFileRepo_GetRemoteFile_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) GetRemoteFile(id interface{}) *MockRemoteFileRepo_GetRemoteFile_Call {
	return &MockRemoteFileRepo_GetRemoteFile_Call{Call: _e.mock.On("GetRemoteFile", id)}
}

func (_c *MockRemoteFileRepo_GetRemoteFile_Call) Run(run func(id int64)) *MockRemoteFileRepo_GetRemoteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRemoteFileRepo_GetRemoteFile_Call) Return(file *models.RemoteFile, err error) *MockRemoteFileRepo_GetRemoteFile_Call {
	_c.Call.Return(file, err)
	return _c
}

// UpdateRemoteFileStatus provides a mock function with given fields: id, status
func (_m *MockRemoteFileRepo) UpdateRemoteFileStatus(id int64, status models.FileStatus) error {
	ret := _m.Called(id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, models.FileStatus) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockRemoteFileRepo_UpdateRemoteFileStatus_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) UpdateRemoteFileStatus(id, status interface{}) *MockRemoteFileRepo_UpdateRemoteFileStatus_Call {
	return &MockRemoteFileRepo_UpdateRemoteFileStatus_Call{Call: _e.mock.On("UpdateRemoteFileStatus", id, status)}
}

func (_c *MockRemoteFileRepo_UpdateRemoteFileStatus_Call) Run(run func(id int64, status models.FileStatus)) *MockRemoteFileRepo_UpdateRemoteFileStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(models.FileStatus))
	})
	return _c
}

func (_c *MockRemoteFileRepo_UpdateRemoteFileStatus_Call) Return(err error) *MockRemoteFileRepo_UpdateRemoteFileStatus_Call {
	_c.Call.Return(err)
	return _c
}

// LinkRemoteFileToJob provides a mock function with given fields: remoteFileID, jobID, status
func (_m *MockRemoteFileRepo) LinkRemoteFileToJob(remoteFileID, jobID int64, status models.FileStatus) error {
	ret := _m.Called(remoteFileID, jobID, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, models.FileStatus) error); ok {
		r0 = rf(remoteFileID, jobID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type MockRemoteFileRepo_LinkRemoteFileToJob_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) LinkRemoteFileToJob(remoteFileID, jobID, status interface{}) *MockRemoteFileRepo_LinkRemoteFileToJob_Call {
	return &MockRemoteFileRepo_LinkRemoteFileToJob_Call{Call: _e.mock.On("LinkRemoteFileToJob", remoteFileID, jobID, status)}
}

func (_c *MockRemoteFileRepo_LinkRemoteFileToJob_Call) Run(run func(remoteFileID, jobID int64, status models.FileStatus)) *MockRemoteFileRepo_LinkRemoteFileToJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(models.FileStatus))
	})
	return _c
}

func (_c *MockRemoteFileRepo_LinkRemoteFileToJob_Call) Return(err error) *MockRemoteFileRepo_LinkRemoteFileToJob_Call {
	_c.Call.Return(err)
	return _c
}

// GetRemoteFilesByPathPrefix provides a mock function with given fields: watchedRoot, pathPrefix
func (_m *MockRemoteFileRepo) GetRemoteFilesByPathPrefix(watchedRoot, pathPrefix string) ([]*models.RemoteFile, error) {
	ret := _m.Called(watchedRoot, pathPrefix)

	var r0 []*models.RemoteFile
	if rf, ok := ret.Get(0).(func(string, string) []*models.RemoteFile); ok {
		r0 = rf(watchedRoot, pathPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RemoteFile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(watchedRoot, pathPrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call struct {
	*mock.Call
}

func (_e *MockRemoteFileRepo_Expecter) GetRemoteFilesByPathPrefix(watchedRoot, pathPrefix interface{}) *MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call {
	return &MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call{Call: _e.mock.On("GetRemoteFilesByPathPrefix", watchedRoot, pathPrefix)}
}

func (_c *MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call) Run(run func(watchedRoot, pathPrefix string)) *MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call) Return(files []*models.RemoteFile, err error) *MockRemoteFileRepo_GetRemoteFilesByPathPrefix_Call {
	_c.Call.Return(files, err)
	return _c
}

// NewMockRemoteFileRepo creates a new instance of MockRemoteFileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRemoteFileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteFileRepo {
	mock := &MockRemoteFileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
