with-expecter: true
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  grabarr/internal/interfaces:
    config:
      dir: "internal/mocks"
      outpkg: mocks
      filename: "mock_{{.InterfaceName}}.go"
    interfaces:
      JobQueue:
      JobExecutor:
      JobRepository:
      ResourceChecker:
      ResourceMonitor:
      SyncService:
      SyncRepository:
      BandwidthMonitor:
      RCloneClient:
      Notifier:
      Gatekeeper: