with-expecter: true
dir: "internal/mocks"
outpkg: mocks
packages:
  grabarr/internal/interfaces:
    interfaces:
      JobQueue:
      JobExecutor:
      JobRepository:
      ResourceChecker:
      ResourceMonitor:
      SyncService:
      SyncRepository:
      BandwidthMonitor:
      RCloneClient: