services:
  grabarr:
    image: grabarr:latest
    container_name: grabarr
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5572:5572"
    user: "99:100"  # Use Unraid nobody user
    volumes:
      # Configuration and data persistence
      - /mnt/user/appdata/grabarr:/config
      - /mnt/user/appdata/grabarr/data:/data

      # Unraid mount points
      - /mnt/user:/unraid/user:rw        # Main array access
      - /mnt/cache:/unraid/cache:rw      # Cache drive access

    env_file:
      - .env  # Load environment variables from .env file

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - proxynet

networks:
  proxynet:
    external: true