services:
  grabarr:
    build: .
    container_name: grabarr
    restart: unless-stopped
    ports:
      - "8080:8080"
    user: "99:100"  # Use Unraid nobody user
    volumes:
      # Configuration files
      - ./config.yaml:/config/config.yaml:ro
      - ./rclone.conf:/config/rclone.conf:ro

      # Web UI files (temporary volume mount solution)
      - ./web/static:/app/web/static:ro

      # Data persistence (local to container directory)
      - ./data:/data

      # Unraid mount points
      - /mnt/user:/unraid/user:rw        # Main array access
      - /mnt/cache:/unraid/cache:rw      # Cache drive access

    env_file:
      - .env  # Load environment variables from .env file

    environment:
      # These will be overridden by .env file if present
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN:-}
      - PUSHOVER_USER=${PUSHOVER_USER:-}
      - TZ=${TZ:-America/New_York}

      # RClone credentials
      - RCLONE_SEEDBOX_HOST=${RCLONE_SEEDBOX_HOST:-}
      - RCLONE_SEEDBOX_USER=${RCLONE_SEEDBOX_USER:-}
      - RCLONE_SEEDBOX_PASS=${RCLONE_SEEDBOX_PASS:-}

    # No resource limits to prevent killing large transfers

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - proxynet

networks:
  proxynet:
    external: true